version: '2'
services:
  amtgardidpapp:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 37080:80
      - 41093:9003
    working_dir: /var/www
    volumes:
      - .:/var/www/idp.amtgard.com
    env_file: .dev.env
    environment:
      - ENVIRONMENT=DEV
    container_name: amtgard-idp
    networks:
      - amtgard-idp-net
    hostname: amtgard-idp-app

  amtgardidpdb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: 'idp'
      # So you don't have to use root, but you can if you like
      MARIADB_USER: 'idp'
      # You can use whatever password you like
      MARIADB_PASSWORD: 'secret'
      # Password for root access
      MARIADB_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '36306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - data-db:/var/lib/mysql
    container_name: amtgard-idp-db
    networks:
      - amtgard-idp-net
    hostname: amtgard-idp-db

volumes:
  data-db: {}

networks:
  amtgard-idp-net: